### ISSUE TITLE
Readme is possibly out of date

### ISSUE THREAD

**Issue by reifying** [ceylon/ceylon.swarm#7]
I am just trying this out for the first time, following the readme: `ceylon install ceylon.swarm`

This fails with `ceylon: 'install' is not a ceylon command`

I am getting this message on both Mac (homebrew) install and Docker image with version 1.3.2

**Comment by reifying** [comment]
I see `ceylon swarm` is already built in and so the ceylon install step just needs to be skipped. It still might be worth updating the readme for newcomers.

**Comment by DiegoCoronel** [comment]
You should try `ceylon plugin install ceylon.swarm`

**Comment by gavinking** [comment]
Thanks, fixed the readme.
